// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Ledger struct {
	ID           uuid.UUID `json: "id"`
	Title        string `json: "title"`
	Members      []uuid.UUID `json: "members"`
	Transactions []int64 `json: "transactions"`
	CreatedAt    time.Time `json: "created_at"`
	UpdatedAt    time.Time `json: "updated_at"`
}

type Transaction struct {
	ID        int64 `json: "id"`
	Debitor   uuid.UUID `json: "debitor"`
	Creditor  uuid.UUID `json: "creditor"`
	Amount    float64 `json: "amount"`
	Note      sql.NullString `json: "note"`
	CreatedAt time.Time	`json: "created_at"`
	UpdatedAt time.Time `json: "updated_at"`
}

type User struct {
	ID        uuid.UUID	`json: "id"`
	Email     string `json: "email"`
	FirstName string `json: "first_name"`
	LastName  sql.NullString `json: "last_name"`
	CreatedAt time.Time	`json: "created_at"`
	UpdatedAt time.Time `json: "updated_at"`
}
